exports.onLogin = "OnLogin"
exports.onSignup = "OnSignup"
exports.onCart = "OnCart"
exports.onOrders = "OnOrders"
exports.onProfile = "OnProfile"
exports.onCheckout = "OnCheckout"
exports.onAddToCart = "OnAddToCart"
exports.onRemoveFromCart = "OnRemoveFromCart"
exports.onUpdateCart = "OnUpdateCart"
exports.onProductsUpload = "OnProductsUpload"
exports.onLogout = "OnLogout"

exports.perFormedproducts = "OnDoneproducts"
exports.perFormedtags = "OnDonetags"
exports.perFormedlogin = "OnDonelogin"
exports.perFormedlogin = "OnDonelogin"
exports.perFormedsignup = "OnDonesignup"
exports.perFormedsignup = "OnDonesignup"
exports.perFormedsignup = "OnDonesignup"
exports.perFormedcart = "OnDonecart"
exports.perFormedorders = "OnDoneorders"
exports.perFormedprofile = "OnDoneprofile"
exports.perFormedcartAction = "OnDonecartAction"
exports.perFormedcartAction = "OnDonecartAction"
exports.perFormedremovedFromCart = "OnDoneremovedFromCart"
exports.perFormedProductsUpload = "OnProductsUpload"
exports.perFormedupdatedCart = "OnDoneupdatedCart"
exports.perFormedLoggedOut = "OnDoneLoggedOut"


